import React, { useState, useEffect } from 'react';
import { generateExcerpt, generateBlogPost } from '../services/geminiService';
import { uploadImage, getUsers, addUser, deleteUser } from '../services/apiService';
import { Article, Category, Banner, User } from '../types';

interface AdminPanelProps {
  onPublish: (article: Article) => Promise<void>;
  categories: Category[];
  onAddCategory: (name: string) => void;
  onDeleteCategory: (id: string) => void;
  banners: Banner[];
  onUpdateBanners: (banners: Banner[]) => void; 
  onAddBanner: (banner: Banner) => Promise<void>;
  onDeleteBanner: (id: string) => void;
  articles: Article[];
  onExit: () => void; 
  onDeleteArticle: (id: string) => void;
}

const AdminPanel: React.FC<AdminPanelProps> = ({ 
    onPublish, 
    categories, 
    onAddCategory, 
    onDeleteCategory,
    banners,
    onAddBanner,
    onDeleteBanner,
    articles,
    onExit,
    onDeleteArticle
}) => {
  const [activeTab, setActiveTab] = useState<'DASHBOARD' | 'ARTICLE' | 'BANNERS' | 'USERS'>('DASHBOARD');
  const [isLoading, setIsLoading] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false); // State para loading da IA
  const [newCategoryName, setNewCategoryName] = useState('');
  const [showCatInput, setShowCatInput] = useState(false);
  
  // State para o filtro de categorias no Dashboard
  const [categoryFilter, setCategoryFilter] = useState('Todas');
  
  // Users Management State
  const [users, setUsers] = useState<User[]>([]);
  const [newUser, setNewUser] = useState({ name: '', email: '', password: '' });

  useEffect(() => {
      if (activeTab === 'USERS') {
          fetchUsers();
      }
  }, [activeTab]);

  const fetchUsers = async () => {
      const fetchedUsers = await getUsers();
      setUsers(fetchedUsers);
  };

  // Article Form State
  const [formData, setFormData] = useState({
    title: '',
    category: categories[0]?.name || '',
    content: '',
    author: 'Equipe Azul 360',
    imageUrl: '',
    imageFile: null as File | null
  });

  // New Banner State
  const [newBanner, setNewBanner] = useState({
      title: '',
      subtitle: '',
      image: '',
      imageFile: null as File | null,
      cta: 'Saiba Mais',
      link: ''
  });

  const handleAddCategorySubmit = (e: React.MouseEvent) => {
      e.preventDefault();
      if(newCategoryName.trim()) {
          onAddCategory(newCategoryName);
          setFormData({...formData, category: newCategoryName});
          setNewCategoryName('');
          setShowCatInput(false);
      }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>, type: 'ARTICLE' | 'BANNER') => {
      const file = e.target.files?.[0];
      if (file) {
          // Preview only
          const objectUrl = URL.createObjectURL(file);
          if (type === 'ARTICLE') {
              setFormData({ ...formData, imageUrl: objectUrl, imageFile: file });
          } else {
              setNewBanner({ ...newBanner, image: objectUrl, imageFile: file });
          }
      }
  };

  const handleGenerateContent = async () => {
      if (!formData.title) {
          alert("Por favor, digite um título ou tópico primeiro para a IA saber sobre o que escrever.");
          return;
      }
      
      setIsGeneratingAI(true);
      try {
          const generatedText = await generateBlogPost(formData.title, formData.category);
          setFormData(prev => ({ ...prev, content: generatedText }));
      } catch (error) {
          alert("Erro ao gerar conteúdo com IA.");
      } finally {
          setIsGeneratingAI(false);
      }
  };

  const handleArticleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title || !formData.content) return;
    setIsUploading(true);

    try {
        let finalImageUrl = formData.imageUrl;
        if (formData.imageFile) {
            // Upload to your PHP server
            finalImageUrl = await uploadImage(formData.imageFile);
        } else if (!finalImageUrl) {
            finalImageUrl = `https://picsum.photos/800/600?random=${Math.floor(Math.random() * 1000)}`;
        }

        const excerpt = await generateExcerpt(formData.content);

        const newArticle: Article = {
            id: '', // Will be generated by MySQL
            title: formData.title,
            content: formData.content,
            category: formData.category,
            imageUrl: finalImageUrl,
            author: formData.author,
            date: new Date().toLocaleDateString('pt-BR', { day: 'numeric', month: 'short', year: 'numeric' }),
            excerpt: excerpt,
            views: 0
        };

        await onPublish(newArticle);
        alert('Artigo publicado com sucesso!');
        setFormData({
            title: '',
            category: categories[0]?.name || '',
            content: '',
            author: 'Equipe Azul 360',
            imageUrl: '',
            imageFile: null
        });
        setActiveTab('DASHBOARD');
    } catch (error) {
        console.error("Failed to publish", error);
        alert("Erro ao publicar artigo. Verifique a conexão.");
    } finally {
        setIsUploading(false);
    }
  };

  const handleAddBannerSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!newBanner.title || !newBanner.image) {
          alert("Título e Imagem são obrigatórios");
          return;
      }
      setIsUploading(true);

      try {
        let finalImageUrl = newBanner.image;
        if (newBanner.imageFile) {
            finalImageUrl = await uploadImage(newBanner.imageFile);
        }

        const bannerToAdd: Banner = {
            id: '', 
            title: newBanner.title,
            subtitle: newBanner.subtitle,
            image: finalImageUrl,
            cta: newBanner.cta,
            link: newBanner.link,
            clicks: 0
        };

        await onAddBanner(bannerToAdd);
        setNewBanner({ title: '', subtitle: '', image: '', imageFile: null, cta: 'Saiba Mais', link: '' });
      } catch (error) {
        alert("Erro ao adicionar banner.");
      } finally {
          setIsUploading(false);
      }
  };

  const handleAddUser = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!newUser.name || !newUser.email || !newUser.password) {
          alert("Preencha todos os campos.");
          return;
      }
      setIsUploading(true);
      try {
          await addUser(newUser.name, newUser.email, newUser.password);
          setNewUser({ name: '', email: '', password: '' });
          await fetchUsers();
          alert("Usuário adicionado com sucesso!");
      } catch (e) {
          alert("Erro ao adicionar usuário.");
      } finally {
          setIsUploading(false);
      }
  };

  const handleDeleteUser = async (id: string) => {
      if(window.confirm("Tem certeza que deseja remover este usuário?")) {
          await deleteUser(id);
          await fetchUsers();
      }
  };

  const handleDeleteArticle = (id: string) => {
      if(window.confirm("Tem certeza que deseja excluir este artigo permanentemente?")) {
          onDeleteArticle(id);
      }
  };

  const totalViews = articles.reduce((acc, curr) => acc + (curr.views || 0), 0);
  const totalBannerClicks = banners.reduce((acc, curr) => acc + (curr.clicks || 0), 0);
  const mostReadArticle = [...articles].sort((a, b) => (b.views || 0) - (a.views || 0))[0];

  // Lógica de filtro para a tabela
  const filteredArticles = categoryFilter === 'Todas' 
      ? articles 
      : articles.filter(article => article.category === categoryFilter);

  return (
    // Max-w-7xl para layout mais largo
    <div className="bg-white rounded-lg shadow-xl p-8 max-w-7xl mx-auto my-10 border border-gray-100 relative">
      
      {(isUploading || isGeneratingAI) && (
          <div className="absolute inset-0 bg-white/90 z-50 flex items-center justify-center rounded-lg backdrop-blur-sm">
              <div className="text-center">
                  {isGeneratingAI ? (
                       <i className="fas fa-magic fa-spin text-5xl text-purple-600 mb-4"></i>
                  ) : (
                       <i className="fas fa-cloud-upload-alt fa-bounce text-5xl text-azul-500 mb-4"></i>
                  )}
                  <p className="font-bold text-xl text-gray-800">
                      {isGeneratingAI ? 'Gemini 3 Pro está escrevendo...' : 'Processando solicitação...'}
                  </p>
                  {isGeneratingAI && <p className="text-sm text-gray-500 mt-2">Criando conteúdo otimizado para {formData.category}</p>}
              </div>
          </div>
      )}

      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 border-b pb-4 gap-4">
        <div className="w-full md:w-auto">
            <div className="flex justify-between items-center w-full">
                <h2 className="text-3xl font-bold text-azul-900">Painel Administrativo</h2>
                
                {/* Botão Voltar ao Site (Mobile) */}
                <button 
                    onClick={onExit}
                    className="md:hidden text-sm font-bold text-gray-500 hover:text-azul-900 flex items-center gap-2 border px-3 py-1 rounded-lg"
                >
                    <i className="fas fa-sign-out-alt"></i> Sair
                </button>
            </div>
            
            <div className="flex gap-4 mt-4 overflow-x-auto">
                <button 
                    onClick={() => setActiveTab('DASHBOARD')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition whitespace-nowrap ${activeTab === 'DASHBOARD' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Dashboard
                </button>
                <button 
                    onClick={() => setActiveTab('ARTICLE')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition whitespace-nowrap ${activeTab === 'ARTICLE' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Novo Artigo
                </button>
                <button 
                    onClick={() => setActiveTab('BANNERS')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition whitespace-nowrap ${activeTab === 'BANNERS' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Banners
                </button>
                <button 
                    onClick={() => setActiveTab('USERS')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition whitespace-nowrap ${activeTab === 'USERS' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Usuários
                </button>
            </div>
        </div>

        {/* Botão Voltar ao Site (Desktop) */}
        <button 
            onClick={onExit}
            className="hidden md:flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg text-gray-600 hover:bg-gray-50 hover:text-azul-900 transition font-semibold text-sm"
        >
            <i className="fas fa-arrow-left"></i> Voltar ao Site
        </button>
      </div>

      {activeTab === 'DASHBOARD' && (
          <div className="animate-fade-in space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="bg-gradient-to-br from-azul-500 to-azul-700 rounded-xl p-6 text-white shadow-lg">
                      <div className="flex justify-between items-start mb-4">
                          <div>
                              <p className="text-blue-100 text-sm font-bold uppercase">Total de Visualizações</p>
                              <h3 className="text-3xl font-bold">{totalViews}</h3>
                          </div>
                          <div className="p-2 bg-white/20 rounded-lg">
                              <i className="fas fa-eye"></i>
                          </div>
                      </div>
                  </div>
                  <div className="bg-gradient-to-br from-purple-500 to-purple-700 rounded-xl p-6 text-white shadow-lg">
                      <div className="flex justify-between items-start mb-4">
                          <div>
                              <p className="text-purple-100 text-sm font-bold uppercase">Cliques em Banners</p>
                              <h3 className="text-3xl font-bold">{totalBannerClicks}</h3>
                          </div>
                          <div className="p-2 bg-white/20 rounded-lg">
                              <i className="fas fa-mouse-pointer"></i>
                          </div>
                      </div>
                  </div>
                  <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                      <p className="text-gray-500 text-xs font-bold uppercase mb-2">Artigo Mais Lido</p>
                      <h3 className="font-bold text-gray-800 line-clamp-2 mb-2">{mostReadArticle?.title || "Nenhum dado"}</h3>
                      <div className="flex items-center text-azul-500 text-sm font-bold">
                          <i className="fas fa-chart-line mr-2"></i>
                          {mostReadArticle?.views || 0} acessos
                      </div>
                  </div>
              </div>

              {/* Table of Articles with Filter */}
              <div>
                  <div className="flex flex-col md:flex-row justify-between items-center mb-4 gap-4">
                      <h3 className="text-xl font-bold text-gray-800">Desempenho dos Artigos</h3>
                      
                      {/* Dropdown de Filtro */}
                      <div className="flex items-center gap-2">
                        <span className="text-sm text-gray-500 font-semibold">Filtrar por:</span>
                        <select 
                            value={categoryFilter}
                            onChange={(e) => setCategoryFilter(e.target.value)}
                            className="p-2 border border-gray-300 rounded-lg text-sm bg-white focus:ring-2 focus:ring-azul-500 outline-none text-gray-700 font-medium"
                        >
                            <option value="Todas">Todas as Categorias</option>
                            {categories.map(cat => (
                                <option key={cat.id} value={cat.name}>{cat.name}</option>
                            ))}
                        </select>
                      </div>
                  </div>

                  <div className="overflow-x-auto rounded-lg border border-gray-200">
                      <table className="w-full text-left border-collapse">
                          <thead>
                              <tr className="bg-gray-50 text-gray-600 text-sm border-b">
                                  <th className="p-4 font-semibold w-5/12">Título</th>
                                  <th className="p-4 font-semibold w-2/12">Categoria</th>
                                  <th className="p-4 font-semibold w-2/12">Autor</th>
                                  <th className="p-4 font-semibold w-1/12 text-center">Views</th>
                                  <th className="p-4 font-semibold w-2/12 text-right">Ações</th>
                              </tr>
                          </thead>
                          <tbody className="text-sm">
                              {filteredArticles.length > 0 ? filteredArticles.map((article) => (
                                  <tr key={article.id} className="border-b hover:bg-gray-50 transition">
                                      <td className="p-4 font-medium text-gray-800">{article.title}</td>
                                      <td className="p-4">
                                          <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full">{article.category}</span>
                                      </td>
                                      <td className="p-4 text-gray-500">{article.author}</td>
                                      <td className="p-4 text-center font-bold text-azul-700">{article.views || 0}</td>
                                      <td className="p-4 text-right">
                                          <button 
                                            onClick={() => handleDeleteArticle(article.id)}
                                            className="text-red-500 hover:text-red-700 font-bold text-xs uppercase border border-red-200 px-3 py-1 rounded hover:bg-red-50 transition"
                                            title="Excluir Artigo"
                                          >
                                            <i className="fas fa-trash mr-1"></i> Remover
                                          </button>
                                      </td>
                                  </tr>
                              )) : (
                                  <tr>
                                      <td colSpan={5} className="p-8 text-center text-gray-400">
                                          Nenhum artigo encontrado nesta categoria.
                                      </td>
                                  </tr>
                              )}
                          </tbody>
                      </table>
                  </div>
              </div>

               {/* Banner Performance */}
               <div>
                  <h3 className="text-xl font-bold text-gray-800 mb-4">Cliques por Banner</h3>
                  <div className="space-y-4">
                      {banners.map(banner => (
                          <div key={banner.id} className="flex items-center gap-4 bg-gray-50 p-4 rounded-lg border border-gray-100">
                              <img src={banner.image} alt="" className="w-16 h-10 object-cover rounded" />
                              <div className="flex-1">
                                  <h4 className="font-bold text-gray-700 text-sm">{banner.title}</h4>
                                  <p className="text-xs text-gray-400 truncate">{banner.link || 'Sem link'}</p>
                                  <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
                                      <div 
                                        className="bg-azul-500 h-2 rounded-full" 
                                        style={{ width: `${Math.min(((banner.clicks || 0) / (totalBannerClicks || 1)) * 100, 100)}%` }}
                                      ></div>
                                  </div>
                              </div>
                              <div className="text-right min-w-[60px]">
                                  <span className="block font-bold text-lg text-azul-900">{banner.clicks || 0}</span>
                                  <span className="text-xs text-gray-500">cliques</span>
                              </div>
                          </div>
                      ))}
                  </div>
              </div>
          </div>
      )}

      {activeTab === 'ARTICLE' && (
        <form onSubmit={handleArticleSubmit} className="space-y-6 animate-fade-in">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Título / Tópico</label>
                <div className="flex gap-2">
                    <input
                        type="text"
                        value={formData.title}
                        onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 focus:border-transparent transition"
                        placeholder="Ex: Tendências de Ecoturismo para 2025"
                    />
                </div>
            </div>

            <div>
                <div className="flex justify-between items-center mb-2">
                    <label className="block text-sm font-semibold text-gray-700">Categoria</label>
                    <button 
                        type="button" 
                        onClick={() => setShowCatInput(!showCatInput)}
                        className="text-xs text-azul-500 font-bold hover:underline"
                    >
                        {showCatInput ? 'Cancelar' : '+ Nova Categoria'}
                    </button>
                </div>
                
                {showCatInput ? (
                    <div className="flex gap-2 mb-2 animate-fade-in items-center">
                        <input 
                            type="text" 
                            value={newCategoryName}
                            onChange={(e) => setNewCategoryName(e.target.value)}
                            placeholder="Nome..."
                            className="flex-1 p-3 border border-gray-300 rounded-lg text-sm"
                        />
                        <button 
                            type="button"
                            onClick={handleAddCategorySubmit}
                            className="bg-green-500 hover:bg-green-600 text-white w-10 h-10 rounded-lg flex items-center justify-center"
                            title="Salvar"
                        >
                            <i className="fas fa-check"></i>
                        </button>
                        <button 
                            type="button"
                            onClick={() => setShowCatInput(false)}
                            className="bg-red-500 hover:bg-red-600 text-white w-10 h-10 rounded-lg flex items-center justify-center"
                            title="Fechar"
                        >
                            <i className="fas fa-times"></i>
                        </button>
                    </div>
                ) : (
                    <>
                    <select
                        value={formData.category}
                        onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 focus:border-transparent transition bg-white"
                    >
                    {categories.map(cat => (
                        <option key={cat.id} value={cat.name}>{cat.name}</option>
                    ))}
                    </select>
                    </>
                )}
            </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">Autor</label>
                    <input
                    type="text"
                    value={formData.author}
                    onChange={(e) => setFormData({ ...formData, author: e.target.value })}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500"
                    />
                </div>
                <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">Imagem de Capa</label>
                    <div className="flex gap-2 items-center">
                        <input
                            type="file"
                            accept="image/*"
                            onChange={(e) => handleImageUpload(e, 'ARTICLE')}
                            className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-azul-50 file:text-azul-700 hover:file:bg-azul-100"
                        />
                        {formData.imageUrl && (
                            <img src={formData.imageUrl} alt="Preview" className="h-10 w-10 object-cover rounded shadow" />
                        )}
                    </div>
                </div>
            </div>
            
            <div>
            <div className="flex justify-between items-end mb-2">
                <label className="block text-sm font-semibold text-gray-700">Conteúdo do Artigo</label>
                <button 
                    type="button" 
                    onClick={handleGenerateContent}
                    className="text-xs bg-purple-100 text-purple-700 hover:bg-purple-200 px-3 py-1 rounded-full font-bold transition flex items-center gap-2"
                >
                    <i className="fas fa-magic"></i> Escrever com IA (Gemini 3 Pro)
                </button>
            </div>
            <div className="relative">
                <textarea
                    value={formData.content}
                    onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                    rows={12}
                    className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 font-mono text-sm leading-relaxed"
                    placeholder="Escreva seu artigo manualmente ou use o botão de IA acima..."
                />
            </div>
            </div>

            <div className="flex justify-end pt-4 border-t">
            <button
                type="submit"
                className="px-8 py-4 bg-azul-900 text-white font-bold rounded-lg hover:bg-azul-700 transition-colors shadow-lg flex items-center gap-2"
            >
                <i className="fas fa-paper-plane"></i> Publicar Artigo
            </button>
            </div>
        </form>
      )}
      
      {activeTab === 'BANNERS' && (
         <div className="animate-fade-in space-y-8">
            <div className="grid grid-cols-1 gap-6">
                {banners.map((banner) => (
                    <div key={banner.id} className="relative group rounded-xl overflow-hidden shadow-md border border-gray-200">
                        <div className="h-40 w-full relative">
                            <img src={banner.image} alt={banner.title} className="w-full h-full object-cover" />
                            <div className="absolute inset-0 bg-black/40"></div>
                            <div className="absolute inset-0 flex items-center p-6">
                                <div className="text-white">
                                    <h3 className="text-xl font-bold">{banner.title}</h3>
                                    <p className="text-sm opacity-90">{banner.subtitle}</p>
                                    <span className="inline-block mt-2 text-xs bg-white/20 px-2 py-1 rounded">{banner.cta}</span>
                                    {banner.link && <p className="text-xs text-blue-200 mt-1 truncate max-w-md"><i className="fas fa-link mr-1"></i> {banner.link}</p>}
                                </div>
                            </div>
                            <div className="absolute top-4 right-4 flex gap-2">
                                <div className="bg-black/50 text-white px-2 py-1 rounded text-xs flex items-center">
                                    <i className="fas fa-mouse-pointer mr-1"></i> {banner.clicks || 0}
                                </div>
                                <button 
                                onClick={() => onDeleteBanner(banner.id)}
                                className="bg-red-600 text-white w-8 h-8 rounded-full flex items-center justify-center hover:bg-red-700 transition"
                            >
                                <i className="fas fa-trash"></i>
                            </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            <div className="bg-gray-50 p-6 rounded-xl border border-gray-200">
                <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <i className="fas fa-plus-circle text-azul-500"></i> Adicionar Novo Banner
                </h3>
                <div className="space-y-4">
                    <div>
                        <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Upload da Imagem</label>
                        <input
                            type="file"
                            accept="image/*"
                            onChange={(e) => handleImageUpload(e, 'BANNER')}
                            className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-azul-50 file:text-azul-700 hover:file:bg-azul-100"
                        />
                        {newBanner.image && <p className="text-xs text-green-600 mt-1"><i className="fas fa-check-circle"></i> Imagem carregada</p>}
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <input 
                            type="text" 
                            placeholder="Título da Campanha"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.title}
                            onChange={(e) => setNewBanner({...newBanner, title: e.target.value})}
                        />
                        <input 
                            type="text" 
                            placeholder="Subtítulo / Descrição Curta"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.subtitle}
                            onChange={(e) => setNewBanner({...newBanner, subtitle: e.target.value})}
                        />
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                         <input 
                            type="text" 
                            placeholder="Texto do Botão (Ex: Saiba Mais)"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.cta}
                            onChange={(e) => setNewBanner({...newBanner, cta: e.target.value})}
                        />
                         <input 
                            type="url" 
                            placeholder="Link de Destino (https://...)"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.link}
                            onChange={(e) => setNewBanner({...newBanner, link: e.target.value})}
                        />
                    </div>
                    <button 
                    onClick={handleAddBannerSubmit}
                    className="w-full bg-azul-900 text-white font-bold py-3 rounded-lg hover:bg-azul-700 transition"
                    >
                        Adicionar Banner
                    </button>
                </div>
            </div>
         </div>
      )}

      {activeTab === 'USERS' && (
          <div className="animate-fade-in space-y-8">
              {/* Add User Form */}
              <div className="bg-gray-50 p-6 rounded-xl border border-gray-200">
                  <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
                      <i className="fas fa-user-plus text-azul-500"></i> Adicionar Novo Administrador
                  </h3>
                  <form onSubmit={handleAddUser} className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <input
                        type="text"
                        placeholder="Nome"
                        className="p-3 border rounded-lg w-full"
                        value={newUser.name}
                        onChange={(e) => setNewUser({...newUser, name: e.target.value})}
                        required
                      />
                      <input
                        type="email"
                        placeholder="E-mail"
                        className="p-3 border rounded-lg w-full"
                        value={newUser.email}
                        onChange={(e) => setNewUser({...newUser, email: e.target.value})}
                        required
                      />
                      <input
                        type="password"
                        placeholder="Senha"
                        className="p-3 border rounded-lg w-full"
                        value={newUser.password}
                        onChange={(e) => setNewUser({...newUser, password: e.target.value})}
                        required
                      />
                      <button 
                        type="submit"
                        className="md:col-span-3 bg-azul-900 text-white font-bold py-3 rounded-lg hover:bg-azul-700 transition"
                      >
                        Cadastrar Usuário
                      </button>
                  </form>
              </div>

              {/* Users List */}
              <div>
                  <h3 className="text-xl font-bold text-gray-800 mb-4">Equipe Cadastrada (Banco de Dados)</h3>
                  <div className="overflow-x-auto rounded-lg border border-gray-200">
                      <table className="w-full text-left border-collapse">
                          <thead>
                              <tr className="bg-gray-50 text-gray-600 text-sm border-b">
                                  <th className="p-4 font-semibold">Nome</th>
                                  <th className="p-4 font-semibold">E-mail</th>
                                  <th className="p-4 font-semibold text-right">Ações</th>
                              </tr>
                          </thead>
                          <tbody className="text-sm">
                              {users.length > 0 ? users.map((user) => (
                                  <tr key={user.id} className="border-b hover:bg-gray-50 transition">
                                      <td className="p-4 font-medium text-gray-800">{user.name}</td>
                                      <td className="p-4 text-gray-500">{user.email}</td>
                                      <td className="p-4 text-right">
                                          <button 
                                            onClick={() => handleDeleteUser(user.id)}
                                            className="text-red-500 hover:text-red-700 font-bold text-xs uppercase border border-red-200 px-2 py-1 rounded hover:bg-red-50 transition"
                                          >
                                            <i className="fas fa-trash mr-1"></i> Remover
                                          </button>
                                      </td>
                                  </tr>
                              )) : (
                                  <tr>
                                      <td colSpan={3} className="p-8 text-center text-gray-400">
                                          Nenhum usuário extra encontrado no banco de dados.
                                      </td>
                                  </tr>
                              )}
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      )}
    </div>
  );
};

export default AdminPanel;