import React, { useState } from 'react';
import { generateBlogPost, generateExcerpt } from '../services/geminiService';
import { uploadImage } from '../services/apiService';
import { Article, Category, Banner } from '../types';

interface AdminPanelProps {
  onPublish: (article: Article) => Promise<void>;
  categories: Category[];
  onAddCategory: (name: string) => void;
  onDeleteCategory: (id: string) => void;
  banners: Banner[];
  onUpdateBanners: (banners: Banner[]) => void; 
  onAddBanner: (banner: Banner) => Promise<void>;
  onDeleteBanner: (id: string) => void;
  articles: Article[];
}

const AdminPanel: React.FC<AdminPanelProps> = ({ 
    onPublish, 
    categories, 
    onAddCategory, 
    onDeleteCategory,
    banners,
    onAddBanner,
    onDeleteBanner,
    articles
}) => {
  const [activeTab, setActiveTab] = useState<'DASHBOARD' | 'ARTICLE' | 'BANNERS'>('DASHBOARD');
  const [isLoading, setIsLoading] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState('');
  const [showCatInput, setShowCatInput] = useState(false);
  
  // Article Form State
  const [formData, setFormData] = useState({
    title: '',
    category: categories[0]?.name || '',
    content: '',
    author: 'Equipe Azul 360',
    imageUrl: '',
    imageFile: null as File | null
  });

  // New Banner State
  const [newBanner, setNewBanner] = useState({
      title: '',
      subtitle: '',
      image: '',
      imageFile: null as File | null,
      cta: 'Saiba Mais'
  });

  const handleGenerate = async () => {
    if (!formData.title) {
      alert("Por favor, insira um título ou tópico para a IA gerar o conteúdo.");
      return;
    }

    setIsLoading(true);
    try {
      const content = await generateBlogPost(formData.title, formData.category);
      setFormData(prev => ({ ...prev, content }));
      setGenerated(true);
    } catch (error) {
      alert("Erro ao gerar conteúdo.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddCategorySubmit = (e: React.MouseEvent) => {
      e.preventDefault();
      if(newCategoryName.trim()) {
          onAddCategory(newCategoryName);
          setFormData({...formData, category: newCategoryName});
          setNewCategoryName('');
          setShowCatInput(false);
      }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>, type: 'ARTICLE' | 'BANNER') => {
      const file = e.target.files?.[0];
      if (file) {
          // Preview only
          const objectUrl = URL.createObjectURL(file);
          if (type === 'ARTICLE') {
              setFormData({ ...formData, imageUrl: objectUrl, imageFile: file });
          } else {
              setNewBanner({ ...newBanner, image: objectUrl, imageFile: file });
          }
      }
  };

  const handleArticleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title || !formData.content) return;
    setIsUploading(true);

    try {
        let finalImageUrl = formData.imageUrl;
        if (formData.imageFile) {
            // Upload to your PHP server
            finalImageUrl = await uploadImage(formData.imageFile);
        } else if (!finalImageUrl) {
            finalImageUrl = `https://picsum.photos/800/600?random=${Math.floor(Math.random() * 1000)}`;
        }

        const excerpt = await generateExcerpt(formData.content);

        const newArticle: Article = {
            id: '', // Will be generated by MySQL
            title: formData.title,
            content: formData.content,
            category: formData.category,
            imageUrl: finalImageUrl,
            author: formData.author,
            date: new Date().toLocaleDateString('pt-BR', { day: 'numeric', month: 'short', year: 'numeric' }),
            excerpt: excerpt,
            views: 0
        };

        await onPublish(newArticle);
        alert('Artigo publicado com sucesso!');
        setFormData({
            title: '',
            category: categories[0]?.name || '',
            content: '',
            author: 'Equipe Azul 360',
            imageUrl: '',
            imageFile: null
        });
        setGenerated(false);
        setActiveTab('DASHBOARD');
    } catch (error) {
        console.error("Failed to publish", error);
        alert("Erro ao publicar artigo. Verifique a conexão.");
    } finally {
        setIsUploading(false);
    }
  };

  const handleAddBannerSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!newBanner.title || !newBanner.image) {
          alert("Título e Imagem são obrigatórios");
          return;
      }
      setIsUploading(true);

      try {
        let finalImageUrl = newBanner.image;
        if (newBanner.imageFile) {
            finalImageUrl = await uploadImage(newBanner.imageFile);
        }

        const bannerToAdd: Banner = {
            id: '', 
            title: newBanner.title,
            subtitle: newBanner.subtitle,
            image: finalImageUrl,
            cta: newBanner.cta,
            clicks: 0
        };

        await onAddBanner(bannerToAdd);
        setNewBanner({ title: '', subtitle: '', image: '', imageFile: null, cta: 'Saiba Mais' });
      } catch (error) {
        alert("Erro ao adicionar banner.");
      } finally {
          setIsUploading(false);
      }
  };

  const totalViews = articles.reduce((acc, curr) => acc + (curr.views || 0), 0);
  const totalBannerClicks = banners.reduce((acc, curr) => acc + (curr.clicks || 0), 0);
  const mostReadArticle = [...articles].sort((a, b) => (b.views || 0) - (a.views || 0))[0];

  return (
    <div className="bg-white rounded-lg shadow-xl p-8 max-w-4xl mx-auto my-10 border border-gray-100 relative">
      
      {isUploading && (
          <div className="absolute inset-0 bg-white/80 z-50 flex items-center justify-center rounded-lg">
              <div className="text-center">
                  <i className="fas fa-cloud-upload-alt fa-bounce text-4xl text-azul-500 mb-2"></i>
                  <p className="font-bold text-azul-900">Enviando dados para o servidor...</p>
              </div>
          </div>
      )}

      {/* ... (Rest of UI remains similar, updating only data binding) ... */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 border-b pb-4 gap-4">
        <div>
            <h2 className="text-3xl font-bold text-azul-900">Painel Administrativo</h2>
            <div className="flex gap-4 mt-4">
                <button 
                    onClick={() => setActiveTab('DASHBOARD')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition ${activeTab === 'DASHBOARD' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Dashboard
                </button>
                <button 
                    onClick={() => setActiveTab('ARTICLE')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition ${activeTab === 'ARTICLE' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Novo Artigo
                </button>
                <button 
                    onClick={() => setActiveTab('BANNERS')}
                    className={`pb-2 px-1 text-sm font-bold uppercase tracking-wider transition ${activeTab === 'BANNERS' ? 'text-azul-500 border-b-2 border-azul-500' : 'text-gray-400 hover:text-gray-600'}`}
                >
                    Banners
                </button>
            </div>
        </div>
      </div>

      {activeTab === 'DASHBOARD' && (
          <div className="animate-fade-in space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="bg-gradient-to-br from-azul-500 to-azul-700 rounded-xl p-6 text-white shadow-lg">
                      <div className="flex justify-between items-start mb-4">
                          <div>
                              <p className="text-blue-100 text-sm font-bold uppercase">Total de Visualizações</p>
                              <h3 className="text-3xl font-bold">{totalViews}</h3>
                          </div>
                          <div className="p-2 bg-white/20 rounded-lg">
                              <i className="fas fa-eye"></i>
                          </div>
                      </div>
                  </div>
                  <div className="bg-gradient-to-br from-purple-500 to-purple-700 rounded-xl p-6 text-white shadow-lg">
                      <div className="flex justify-between items-start mb-4">
                          <div>
                              <p className="text-purple-100 text-sm font-bold uppercase">Cliques em Banners</p>
                              <h3 className="text-3xl font-bold">{totalBannerClicks}</h3>
                          </div>
                          <div className="p-2 bg-white/20 rounded-lg">
                              <i className="fas fa-mouse-pointer"></i>
                          </div>
                      </div>
                  </div>
                  <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                      <p className="text-gray-500 text-xs font-bold uppercase mb-2">Artigo Mais Lido</p>
                      <h3 className="font-bold text-gray-800 line-clamp-2 mb-2">{mostReadArticle?.title || "Nenhum dado"}</h3>
                      <div className="flex items-center text-azul-500 text-sm font-bold">
                          <i className="fas fa-chart-line mr-2"></i>
                          {mostReadArticle?.views || 0} acessos
                      </div>
                  </div>
              </div>

              {/* Table of Articles */}
              <div>
                  <h3 className="text-xl font-bold text-gray-800 mb-4">Desempenho dos Artigos</h3>
                  <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse">
                          <thead>
                              <tr className="bg-gray-50 text-gray-600 text-sm border-b">
                                  <th className="p-4 font-semibold">Título</th>
                                  <th className="p-4 font-semibold">Categoria</th>
                                  <th className="p-4 font-semibold">Autor</th>
                                  <th className="p-4 font-semibold text-right">Views</th>
                              </tr>
                          </thead>
                          <tbody className="text-sm">
                              {articles.map((article) => (
                                  <tr key={article.id} className="border-b hover:bg-gray-50 transition">
                                      <td className="p-4 font-medium text-gray-800">{article.title}</td>
                                      <td className="p-4">
                                          <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full">{article.category}</span>
                                      </td>
                                      <td className="p-4 text-gray-500">{article.author}</td>
                                      <td className="p-4 text-right font-bold text-azul-700">{article.views || 0}</td>
                                  </tr>
                              ))}
                          </tbody>
                      </table>
                  </div>
              </div>

               {/* Banner Performance */}
               <div>
                  <h3 className="text-xl font-bold text-gray-800 mb-4">Cliques por Banner</h3>
                  <div className="space-y-4">
                      {banners.map(banner => (
                          <div key={banner.id} className="flex items-center gap-4 bg-gray-50 p-4 rounded-lg border border-gray-100">
                              <img src={banner.image} alt="" className="w-16 h-10 object-cover rounded" />
                              <div className="flex-1">
                                  <h4 className="font-bold text-gray-700 text-sm">{banner.title}</h4>
                                  <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
                                      <div 
                                        className="bg-azul-500 h-2 rounded-full" 
                                        style={{ width: `${Math.min(((banner.clicks || 0) / (totalBannerClicks || 1)) * 100, 100)}%` }}
                                      ></div>
                                  </div>
                              </div>
                              <div className="text-right min-w-[60px]">
                                  <span className="block font-bold text-lg text-azul-900">{banner.clicks || 0}</span>
                                  <span className="text-xs text-gray-500">cliques</span>
                              </div>
                          </div>
                      ))}
                  </div>
              </div>
          </div>
      )}

      {activeTab === 'ARTICLE' && (
        <form onSubmit={handleArticleSubmit} className="space-y-6 animate-fade-in">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Título / Tópico</label>
                <input
                type="text"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 focus:border-transparent transition"
                placeholder="Ex: Tendências de Ecoturismo para 2025"
                />
            </div>

            <div>
                <div className="flex justify-between items-center mb-2">
                    <label className="block text-sm font-semibold text-gray-700">Categoria</label>
                    <button 
                        type="button" 
                        onClick={() => setShowCatInput(!showCatInput)}
                        className="text-xs text-azul-500 font-bold hover:underline"
                    >
                        {showCatInput ? 'Cancelar' : '+ Nova Categoria'}
                    </button>
                </div>
                
                {showCatInput ? (
                    <div className="flex gap-2 mb-2 animate-fade-in items-center">
                        <input 
                            type="text" 
                            value={newCategoryName}
                            onChange={(e) => setNewCategoryName(e.target.value)}
                            placeholder="Nome..."
                            className="flex-1 p-3 border border-gray-300 rounded-lg text-sm"
                        />
                        <button 
                            type="button"
                            onClick={handleAddCategorySubmit}
                            className="bg-green-500 hover:bg-green-600 text-white w-10 h-10 rounded-lg flex items-center justify-center"
                            title="Salvar"
                        >
                            <i className="fas fa-check"></i>
                        </button>
                        <button 
                            type="button"
                            onClick={() => setShowCatInput(false)}
                            className="bg-red-500 hover:bg-red-600 text-white w-10 h-10 rounded-lg flex items-center justify-center"
                            title="Fechar"
                        >
                            <i className="fas fa-times"></i>
                        </button>
                    </div>
                ) : (
                    <>
                    <select
                        value={formData.category}
                        onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 focus:border-transparent transition bg-white"
                    >
                    {categories.map(cat => (
                        <option key={cat.id} value={cat.name}>{cat.name}</option>
                    ))}
                    </select>
                    </>
                )}
            </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">Autor</label>
                    <input
                    type="text"
                    value={formData.author}
                    onChange={(e) => setFormData({ ...formData, author: e.target.value })}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500"
                    />
                </div>
                <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">Imagem de Capa</label>
                    <div className="flex gap-2 items-center">
                        <input
                            type="file"
                            accept="image/*"
                            onChange={(e) => handleImageUpload(e, 'ARTICLE')}
                            className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-azul-50 file:text-azul-700 hover:file:bg-azul-100"
                        />
                        {formData.imageUrl && (
                            <img src={formData.imageUrl} alt="Preview" className="h-10 w-10 object-cover rounded shadow" />
                        )}
                    </div>
                </div>
            </div>
            
            {!generated && (
                <div className="bg-azul-50 p-6 rounded-xl border border-blue-100 flex flex-col md:flex-row items-center justify-between gap-4">
                    <div className="text-azul-900">
                        <h4 className="font-bold"><i className="fas fa-magic mr-2"></i>Assistente de Escrita AI</h4>
                        <p className="text-sm opacity-80">Deixe o Gemini criar um rascunho completo baseado no título acima.</p>
                    </div>
                    <button
                        type="button"
                        onClick={handleGenerate}
                        disabled={isLoading || !formData.title}
                        className={`px-6 py-3 rounded-lg font-bold text-white shadow-lg flex items-center gap-2 transition-all transform hover:-translate-y-1 ${isLoading ? 'bg-gray-400 cursor-not-allowed' : 'bg-gradient-to-r from-azul-700 to-azul-500 hover:shadow-azul-500/30'}`}
                    >
                        {isLoading ? (
                            <><i className="fas fa-circle-notch fa-spin"></i> Gerando (Gemini Thinking)...</>
                        ) : (
                            <><i className="fas fa-pen-nib"></i> Gerar Rascunho</>
                        )}
                    </button>
                </div>
            )}

            <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Conteúdo do Artigo (Markdown)</label>
            <div className="relative">
                <textarea
                    value={formData.content}
                    onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                    rows={12}
                    className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-azul-500 font-mono text-sm leading-relaxed"
                    placeholder="# Escreva seu artigo ou gere com IA..."
                />
            </div>
            </div>

            <div className="flex justify-end pt-4 border-t">
            <button
                type="submit"
                className="px-8 py-4 bg-azul-900 text-white font-bold rounded-lg hover:bg-azul-700 transition-colors shadow-lg flex items-center gap-2"
            >
                <i className="fas fa-paper-plane"></i> Publicar Artigo
            </button>
            </div>
        </form>
      )}
      
      {activeTab === 'BANNERS' && (
         <div className="animate-fade-in space-y-8">
            <div className="grid grid-cols-1 gap-6">
                {banners.map((banner) => (
                    <div key={banner.id} className="relative group rounded-xl overflow-hidden shadow-md border border-gray-200">
                        <div className="h-40 w-full relative">
                            <img src={banner.image} alt={banner.title} className="w-full h-full object-cover" />
                            <div className="absolute inset-0 bg-black/40"></div>
                            <div className="absolute inset-0 flex items-center p-6">
                                <div className="text-white">
                                    <h3 className="text-xl font-bold">{banner.title}</h3>
                                    <p className="text-sm opacity-90">{banner.subtitle}</p>
                                    <span className="inline-block mt-2 text-xs bg-white/20 px-2 py-1 rounded">{banner.cta}</span>
                                </div>
                            </div>
                            <div className="absolute top-4 right-4 flex gap-2">
                                <div className="bg-black/50 text-white px-2 py-1 rounded text-xs flex items-center">
                                    <i className="fas fa-mouse-pointer mr-1"></i> {banner.clicks || 0}
                                </div>
                                <button 
                                onClick={() => onDeleteBanner(banner.id)}
                                className="bg-red-600 text-white w-8 h-8 rounded-full flex items-center justify-center hover:bg-red-700 transition"
                            >
                                <i className="fas fa-trash"></i>
                            </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            <div className="bg-gray-50 p-6 rounded-xl border border-gray-200">
                <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <i className="fas fa-plus-circle text-azul-500"></i> Adicionar Novo Banner
                </h3>
                <div className="space-y-4">
                    <div>
                        <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Upload da Imagem</label>
                        <input
                            type="file"
                            accept="image/*"
                            onChange={(e) => handleImageUpload(e, 'BANNER')}
                            className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-azul-50 file:text-azul-700 hover:file:bg-azul-100"
                        />
                        {newBanner.image && <p className="text-xs text-green-600 mt-1"><i className="fas fa-check-circle"></i> Imagem carregada</p>}
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <input 
                            type="text" 
                            placeholder="Título da Campanha"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.title}
                            onChange={(e) => setNewBanner({...newBanner, title: e.target.value})}
                        />
                        <input 
                            type="text" 
                            placeholder="Subtítulo / Descrição Curta"
                            className="p-3 border rounded-lg w-full"
                            value={newBanner.subtitle}
                            onChange={(e) => setNewBanner({...newBanner, subtitle: e.target.value})}
                        />
                    </div>
                    <input 
                        type="text" 
                        placeholder="Texto do Botão (Ex: Saiba Mais)"
                        className="p-3 border rounded-lg w-full"
                        value={newBanner.cta}
                        onChange={(e) => setNewBanner({...newBanner, cta: e.target.value})}
                    />
                    <button 
                    onClick={handleAddBannerSubmit}
                    className="w-full bg-azul-900 text-white font-bold py-3 rounded-lg hover:bg-azul-700 transition"
                    >
                        Adicionar Banner
                    </button>
                </div>
            </div>
         </div>
      )}
    </div>
  );
};

export default AdminPanel;